'use strict';
const D=window.GUIDE_DATA,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=p=>p.split('#').map((part,i)=>i?part:part.split('/').map(encodeURIComponent).join('/')).join('#');
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem('guide:'+k))??d}catch{return d}},put=(k,v)=>{try{localStorage.setItem('guide:'+k,JSON.stringify(v))}catch{}};
let current=D.cases.find(c=>c.id===location.hash.slice(1))||D.cases[0],views={normal:0,lesion:0},saved=new Set(get('saved',[])),onlySaved=false,showChinese=get('chinese',true),practice=false,variantIndex=0;
function applyLanguage(){document.body.classList.toggle('en-only',!showChinese);$('#language').textContent=showChinese?'英文＋中文':'英文作答模式';$('#language').setAttribute('aria-pressed',showChinese)}
$('#language').onclick=()=>{showChinese=!showChinese;put('chinese',showChinese);applyLanguage()};applyLanguage();
Object.entries(D.lessons).sort(([a],[b])=>a.localeCompare(b)).forEach(([v,t])=>$('#lesson').add(new Option(`${v.slice(0,2)}/${v.slice(2)} · ${t}`,v)));
function filtered(){const q=$('#search').value.trim().toLowerCase(),lesson=$('#lesson').value;return D.cases.filter(c=>(!lesson||c.date===lesson)&&(!onlySaved||saved.has(c.id))&&(!q||q.split(/\s+/).every(w=>[c.id,c.diagnosis,c.zh,c.organ,c.lesson,D.normals[c.normal].name,c.caution,...c.pairs.map(p=>p.en+' '+p.zh),...(c.transcriptReview.teacherNotes||[])].join(' ').toLowerCase().includes(w))))}
function renderNav(){const list=filtered();$('#result-count').textContent=`${list.length} / ${D.cases.length} 主題`;let last='';$('#case-list').innerHTML=list.length?list.map(c=>{let heading=last!==c.date?`<p class="group-label">${c.date.slice(0,2)}/${c.date.slice(2)} · ${esc(c.lesson)}</p>`:'';last=c.date;return heading+`<a class="case-link" href="#${c.id}" ${c.id===current.id?'aria-current="page"':''}><small>${esc(c.id)} · ${esc(c.organ)} ${saved.has(c.id)?'●':''}</small>${esc(c.zh)}</a>`}).join(''):'<p class="empty">沒有符合的切片。可清除搜尋或切回全部講次。</p>';const idx=list.findIndex(c=>c.id===current.id);$('#position').textContent=idx>=0?`${idx+1} / ${list.length}`:'目前切片不在篩選結果中';$('#previous').disabled=idx<=0;$('#next').disabled=idx<0||idx>=list.length-1}
$('#search').oninput=renderNav;$('#lesson').onchange=renderNav;$('#only-saved').onclick=()=>{onlySaved=!onlySaved;$('#only-saved').setAttribute('aria-pressed',onlySaved);renderNav()};
for(const [id,step] of [['previous',-1],['next',1]])$('#'+id).onclick=()=>{const l=filtered(),i=l.findIndex(c=>c.id===current.id);if(l[i+step])location.hash=l[i+step].id};
$('#menu').onclick=()=>{const on=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',on)};
function viewList(side){return side==='normal'?D.normals[current.normal].images:current.images}
function panel(side){const n=D.normals[current.normal],title=side==='normal'?n.name:current.zh;return `<section class="panel"><div class="panel-head"><div class="step">${side==='normal'?'01 / ORGAN':'02 / LESION'}</div><h2>${esc(title)}</h2><div class="views" aria-label="${side==='normal'?'正常構造':'病變'}視野">${viewList(side).map((im,i)=>`<button data-side="${side}" data-view="${i}" aria-pressed="${views[side]===i}">${esc(im.label)}</button>`).join('')}</div></div><button class="imagebutton" data-open="${side}" aria-label="放大${esc(title)}圖片"><img id="${side}-image" alt=""><span class="enlarge">＋ 點圖放大</span></button><div class="caption" id="${side}-caption"></div><div class="reading"><h3>${side==='normal'?'先用哪些構造認器官？':'這個視野怎麼讀？'}</h3><p id="${side}-guide"></p></div></section>`}
function updateView(side){const im=viewList(side)[views[side]];$('#'+side+'-image').src=link(im.src);$('#'+side+'-image').alt=im.label+'；'+im.guide;$('#'+side+'-caption').innerHTML=esc(shortCaption(im));$('#'+side+'-guide').textContent=im.guide;document.querySelectorAll(`[data-side="${side}"]`).forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.view)===views[side]))}
function reviewHTML(){const r=current.transcriptReview;if(!r.teacherNotes?.length)return '';return `<section class="teacher"><h2>老師提醒 · 課堂補充</h2><ul>${r.teacherNotes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></section>`}
function shortCaption(im){return im.label}
function absent(p){return /本片無|本片沒有|not present in this slide/i.test(p.en+' '+p.zh)}
function answerHTML(items){return items.map(p=>`<div class="answer"><p class="english">${esc(p.en)}</p><p class="chinese">${esc(p.zh)}</p></div>`).join('')}
function renderCase(){const c=current,n=D.normals[c.normal],r=c.transcriptReview;document.title=`${c.zh} · ${c.id}｜切片導讀`;$('#case').innerHTML=`
<div class="hero"><div><div class="eyebrow">${c.id} · ${c.date.slice(0,2)}/${c.date.slice(2)} · ${esc(c.lesson)}</div><h1>${esc(c.zh)}</h1><p class="subtitle">${esc(c.diagnosis)}</p></div><div class="organ"><div><small>本教學片器官</small><strong>${esc(c.organ)}</strong></div><button id="save" aria-pressed="${saved.has(c.id)}">${saved.has(c.id)?'已列待複習':'＋ 待複習'}</button></div></div>
<p class="intro"><b>先認器官，再描述病變。</b>正常對照與病變圖不是同一標本的前後變化；原圖箭頭沿用講義，不新增未驗證的病灶定位。${['valve','sinonasal','oral'].includes(c.normal)?' 本頁左側為病片的保留構造參照，並非正常標本。':''}</p>
<p class="online-slides">線上玻片：<a target="_blank" rel="noopener" href="https://dpaiext.ntuh.gov.tw/dpai/slide/virtual-slide-box/a98db8da-e9c0-4787-9119-0319d2872d07/">EX1.1</a> · <a target="_blank" rel="noopener" href="https://dpaiext.ntuh.gov.tw/dpai/slide/virtual-slide-box/bdca4c2d-079e-4834-85b5-9f412f8143a8/">EX1.2</a> · 密碼 0000</p>${c.id==="PA0354"?"<p>本機無 PA0354 原片；以下使用講義圖片。</p>":""}<div class="grid">${panel('normal')}${panel('lesion')}</div><p class="scale-note">兩側倍率與尺度不同，不可直接比較畫面中的細胞大小。HI 全景為縮圖；精細辨識請搭配講義高倍圖。</p>
<div class="content-grid"><section><div class="sectionhead"><h2>英文作答，中文理解</h2><button id="practice-toggle">${practice?'顯示參考答案':'先練英文描述'}</button></div><div class="practice ${practice?'':'hidden'}"><label for="draft">Organ / Diagnosis / Description</label><textarea id="draft" placeholder="先用英文寫下你看到的構造和病變…"></textarea><small>文字只保存在此瀏覽器；此功能不自動評分。</small></div><div id="answers" class="${practice?'hidden':''}"><div class="answer"><p class="english">Organ: ${esc(c.organ)}</p><p class="english">Diagnosis: ${esc(c.diagnosis)}</p></div><p class="source-pages">${c.date.slice(0,2)}/${c.date.slice(2)} 講義 p.${(c.sourcePages||[]).join("、")}</p>${answerHTML(c.pairs.filter(p=>!absent(p)))}${c.pairs.some(absent)?`<section class="extra"><h3>講義列出、本片無</h3>${answerHTML(c.pairs.filter(absent))}</section>`:""}${c.extra.length?`<div class="extra"><h3>${esc("附加描述 · 課堂補充")}</h3>${answerHTML(c.extra)}</div>`:''}</div><p class="cross-intro">依本教學片整理；換片後重新確認，不把整段直接套用。</p></section><aside><section class="warning"><h2>這片最容易混淆的地方</h2><p>${esc(c.caution)}</p></section>${reviewHTML()}</aside></div>
<section class="cross"><h2>換器官、換階段，怎麼認？</h2><p class="cross-intro">病變模式不是器官名稱。以下只列課堂已有例子；正常構造需回到保存較好的區域確認。</p>${c.variants.length?`<div class="variants">${c.variants.map((v,i)=>`<button data-variant="${i}" aria-pressed="${i===variantIndex}">${esc(v.title)}</button>`).join('')}</div><div id="cross-body"></div>`:`<p class="cross-intro">${esc(n.guide)} 若此視野只剩壞死、菌體或疤痕，應保留器官判斷，回看低倍或標本資料。</p>`}${c.related.length?`<h3>用同一組問題比較其他教學片</h3><div class="related">${c.related.map(id=>{let o=D.cases.find(x=>x.id===id);return `<a href="#${id}">${esc(o.zh)} · ${esc(o.organ)}</a>`}).join('')}</div><p class="cross-intro">比較共同模式與差異，並非把這些診斷視為同義詞。</p>`:''}</section>
`;
 $('#save').onclick=()=>{saved.has(c.id)?saved.delete(c.id):saved.add(c.id);put('saved',[...saved]);$('#save').textContent=saved.has(c.id)?'已列待複習':'＋ 待複習';$('#save').setAttribute('aria-pressed',saved.has(c.id));renderNav()};
 $('#practice-toggle').onclick=()=>{practice=!practice;$('#answers').classList.toggle('hidden',practice);$('.practice').classList.toggle('hidden',!practice);$('#practice-toggle').textContent=practice?'顯示參考答案':'先練英文描述'};$('#draft').value=get('draft:'+c.id,'');$('#draft').oninput=()=>put('draft:'+c.id,$('#draft').value);
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{views[b.dataset.side]=Number(b.dataset.view);updateView(b.dataset.side)});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openImage(viewList(b.dataset.open)[views[b.dataset.open]]));document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>{variantIndex=Number(b.dataset.variant);renderVariant()});updateView('normal');updateView('lesion');if(c.variants.length)renderVariant();renderNav();}
function renderVariant(){const v=current.variants[variantIndex],n=D.normals[v.normal],im=n.images[0];$('#cross-body').innerHTML=`<div class="cross-body"><div><h3>${esc(n.name)} · 正常／構造參照</h3><button class="imagebutton" id="cross-normal"><img src="${link(im.src)}" alt="${esc(im.label)}"><span class="enlarge">＋ 放大</span></button><small>${esc(shortCaption(im))}</small><p>${esc(n.guide)}</p></div><div><h3>${esc(v.title)}</h3><p>${esc(v.note)}</p>${v.images.length?v.images.map((im,i)=>`<button class="imagebutton" data-cross-image="${i}"><img loading="lazy" src="${link(im.src)}" alt="${esc(im.label)}"><span class="enlarge">＋ 放大</span></button><small>${esc(shortCaption(im))}</small><p>${esc(im.guide)}</p>`).join(''):'<p class="empty">此對照提供正常組織及課堂來源。</p>'}</div></div>`;$('#cross-normal').onclick=()=>openImage(im);document.querySelectorAll('[data-cross-image]').forEach(b=>b.onclick=()=>openImage(v.images[Number(b.dataset.crossImage)]));document.querySelectorAll('[data-variant]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.variant)===variantIndex))}
function openImage(im){$('#modal-title').textContent=im.label;$('#modal-image').src=link(im.src);$('#modal-image').alt=im.guide||im.label;$('#viewer').classList.remove('zoom');$('#zoom').textContent='放大 180%';$('#lightbox').showModal()}
$('#close').onclick=()=>$('#lightbox').close();$('#zoom').onclick=()=>{const on=$('#viewer').classList.toggle('zoom');$('#zoom').textContent=on?'符合視窗':'放大 180%'};
window.addEventListener('hashchange',()=>{const c=D.cases.find(c=>c.id===location.hash.slice(1));if(!c)return;current=c;views={normal:0,lesion:0};variantIndex=0;practice=false;$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');renderCase();window.scrollTo({top:0})});renderCase();
